# Generated by Django 4.2.5 on 2023-11-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64, verbose_name='Хэш')),
                ('ciphertext', models.TextField(verbose_name='Зашифрованный текст')),
                ('link', models.CharField(max_length=250, verbose_name='Ссылка')),
                ('lifetime', models.PositiveSmallIntegerField(verbose_name='Время жизни')),
                ('code_frase', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name': 'Секрет',
                'verbose_name_plural': 'Секреты',
            },
        ),
    ]
