# Generated by Django 4.2.5 on 2023-11-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_secret', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='code_frase',
        ),
        migrations.RemoveField(
            model_name='secret',
            name='hash',
        ),
        migrations.AddField(
            model_name='secret',
            name='code_phrase',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Хэш'),
        ),
        migrations.AddField(
            model_name='secret',
            name='is_code_phrase',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='secret',
            name='link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка'),
        ),
    ]
