# Generated by Django 4.2.5 on 2023-11-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_secret', '0002_remove_secret_code_frase_remove_secret_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='time_to_delete',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время удаления'),
        ),
    ]
