# Generated by Django 4.2.5 on 2023-11-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_secret', '0003_secret_time_to_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='secret_text',
            field=models.TextField(blank=True, null=True, verbose_name='Cекретный текст'),
        ),
    ]
